/* eslint-disable @typescript-eslint/no-misused-promises */
import Head from "next/head";
import { api } from "@/utils/api";
import ReactFullpage from "@fullpage/react-fullpage";

import Image from "next/image";
// Page 1
import title from "@/images/title.png";
import credits from "@/images/credits.png";
import assets_1 from "@/images/asset_1.png";
// Page 2
import schedule_eng from "@/images/schedule_eng.png";
import schedule_chi from "@/images/schedule_chi.png";
import masterclass_venue from "@/images/masterclass_venue.png";
// Page 3
import connection_title from "@/images/connection_title.png";
import plus_button from "@/images/plus_button.png";
import add_your_connection from "@/images/add_your_connection.png";
import modal_title from "@/images/modal_title.png";

// Icons
import facebook from "@/images/facebook.png";
import instagram from "@/images/instagram.png";
import youtube from "@/images/youtube.png";
import whatsapp from "@/images/whatsapp.png";
import close_button from "@/images/close_button.png";

import { useEffect, useState } from "react";

import "swiper/css";
import "swiper/css/effect-cards";
// import required modules
import { EffectCards } from "swiper/modules";
import { Swiper, SwiperSlide } from "swiper/react";
import Link from "next/link";

import { Dialog, DialogBackdrop, DialogPanel } from "@headlessui/react";
import { CardForm } from "@/components/Form";
// import { Card } from "@prisma/client";

export default function Home() {
  const cards = api.post.create.useMutation();
  const allCards = api.post.allCards.useQuery();
  const [en, setEn] = useState(true);
  const [modalOpen, setModalOpen] = useState(false);

  // cards.mutate()

  useEffect(() => {
    const interval = setInterval(async () => await allCards.refetch(), 5000);
    return () => clearInterval(interval);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
  return (
    <>
      <Head>
        <title>The Blessing Conference</title>
        {/* <meta name="description" content="Generated by create-t3-app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <ReactFullpage
        credits={{
          enabled: false,
        }}
        render={({ fullpageApi }) => (
          <ReactFullpage.Wrapper>
            <div className="section relative h-full bg-[url('/bg.jpeg')] bg-cover bg-center bg-no-repeat">
              <Image
                src={credits}
                alt="Credits"
                className="absolute left-1/2 top-[50px] max-w-[75px] -translate-x-1/2 xs:max-w-[115px]"
              />
              <Image
                src={title}
                alt="BlessConf Title"
                className="shimmer absolute left-1/2 top-1/2 max-w-[250px] -translate-x-1/2 -translate-y-1/2 xs:max-w-[300px]"
              />
              <Image
                src={assets_1}
                alt="Asset 1"
                className="absolute bottom-0 left-1/2 z-10 max-w-[150px] -translate-x-1/2 translate-y-1/2 rotate-[147deg]"
              />
            </div>
            <div className="section relative flex h-full flex-col items-center justify-center bg-[url('/bg_2.jpeg')] bg-cover bg-center bg-no-repeat">
              <Image
                onClick={() => setEn((prev) => !prev)}
                src={schedule_eng}
                alt="Eng Schedule"
                className={`${en ? "opacity-100" : "opacity-0"} absolute left-1/2 top-1/2 z-[5] max-w-[300px] -translate-x-1/2 -translate-y-1/2 transition-opacity duration-500 ease-in-out xs:max-w-[375px]`}
              />

              <Image
                onClick={() => setEn((prev) => !prev)}
                src={schedule_chi}
                alt="Chi Schedule"
                className={`absolute left-1/2 top-1/2 max-w-[300px] -translate-x-1/2 -translate-y-1/2 xs:max-w-[375px]`}
              />
              <Image
                src={masterclass_venue}
                alt="Masterclass Venue"
                className={`absolute bottom-7 left-1/2 max-w-[280px] -translate-x-1/2 xs:bottom-10 xs:max-w-[340px]`}
              />
            </div>
            <div className="section relative h-full bg-[url('/bg.jpeg')] bg-cover bg-center bg-no-repeat">
              <Image
                src={connection_title}
                alt="Connection"
                className="absolute left-1/2 top-[50px] max-w-[220px] -translate-x-1/2 xs:max-w-[250px]"
              />
              <div className="mt-[43px] flex h-full flex-col items-center gap-[22px]">
                <div
                  style={{
                    boxShadow: "0 4px 10px 0 #00000040",
                  }}
                  className="flex h-[170px] w-[290px] flex-col items-center justify-center gap-[13px] rounded-xl bg-white"
                >
                  <Image
                    src={plus_button}
                    alt="Plus Button"
                    className="h-[46px] w-[46px]"
                    onClick={() => setModalOpen(true)}
                  />
                  <Image
                    src={add_your_connection}
                    alt="Add Your Connection"
                    className="max-w-[173px]"
                    onClick={() => setModalOpen(true)}
                  />
                </div>
                <Swiper
                  effect={"cards"}
                  grabCursor={true}
                  modules={[EffectCards]}
                >
                  {allCards.data?.map((c) => (
                    <SwiperSlide
                      key={c.id}
                      className="flex flex-col rounded-xl border border-black/10 bg-[#ededed]"
                      style={{
                        boxShadow: "0 4px 10px 0 #00000040",
                      }}
                    >
                      <div className="flex h-[140px] flex-col rounded-xl bg-white px-[18px] py-[21px] font-sf">
                        <p className="text-[15px] font-bold">{c.name}</p>
                        <p className="text-[10px]">{c.company}</p>
                        <p className="text-[8px]">{c.position}</p>
                      </div>
                      <div className="flex h-[40px] flex-row items-center justify-between px-4">
                        <p className="text-[10px]">{c.contact}</p>
                        <Image
                          src={connection_title}
                          alt="Connection Title"
                          className="max-w-[60px]"
                        />
                      </div>
                    </SwiperSlide>
                  ))}
                </Swiper>
              </div>
              <div className="absolute bottom-[14px] left-1/2 flex -translate-x-1/2 flex-col items-center gap-2">
                <p className="font-sf text-sm font-bold">Follow Us</p>
                <div className="flex flex-row items-center gap-[14px]">
                  <Image
                    src={instagram}
                    alt="Instagram"
                    className="max-w-[33px]"
                    onClick={() =>
                      window.open("https://www.instagram.com/fgacyc", "_blank")
                    }
                  />
                  <Image
                    src={facebook}
                    alt="Facebook"
                    className="max-w-[33px]"
                    onClick={() =>
                      window.open("https://www.facebook.com/fgacyc", "_blank")
                    }
                  />
                  <Image
                    src={youtube}
                    alt="Youtube"
                    className="max-w-[33px]"
                    onClick={() =>
                      window.open("https://www.youtube.com/@fgacyc", "_blank")
                    }
                  />
                  <Image
                    src={whatsapp}
                    alt="WhatsApp"
                    className="max-w-[33px]"
                    onClick={() =>
                      window.open("https://wa.me/+601127009925", "_blank")
                    }
                  />
                </div>
                <Link
                  href={"https://www.fgacyc.com"}
                  className="text-xs font-bold"
                >
                  fgacyc.com
                </Link>
              </div>
            </div>
          </ReactFullpage.Wrapper>
        )}
      ></ReactFullpage>
      <Dialog
        open={modalOpen}
        as="div"
        className="relative z-10 font-sf focus:outline-none"
        onClose={() => setModalOpen(false)}
      >
        <DialogBackdrop
          transition
          className="fixed inset-0 bg-black/30 duration-300 ease-out data-[closed]:opacity-0"
        />
        <div className="fixed inset-0 z-10 w-screen overflow-y-auto">
          <div className="flex min-h-full items-center justify-center p-4">
            <DialogPanel
              transition
              className="data-[closed]:transform-[scale(95%)] relative flex w-full max-w-md flex-col items-center rounded-xl bg-white px-10 pb-6 pt-[52px] backdrop-blur-2xl duration-300 ease-out data-[closed]:opacity-0"
            >
              <Image
                src={close_button}
                alt="Close Button"
                role="button"
                onClick={() => setModalOpen(false)}
                className="absolute right-4 top-4 max-w-[15px]"
              />

              <Image
                src={modal_title}
                alt="Modal Title"
                className="max-w-[190px]"
              />

              <div className="flex w-full flex-col items-center gap-3">
                <CardForm
                  // onClose={() => setModalOpen(false)}
                  onSubmit={(e, resetForm) => {
                    cards.mutate(
                      {
                        company: String(e.company),
                        name: String(e.name),
                        contact: String(e.contact),
                        position: String(e.position),
                      },
                      {
                        onSuccess: () => {
                          setModalOpen(false);
                          resetForm();
                        },
                      },
                    );
                  }}
                />
              </div>
            </DialogPanel>
          </div>
        </div>
      </Dialog>
    </>
  );
}
